version: "3"

services:
  nginx-load-balancer:
    image: nginx:latest
    container_name: nginx-load-balancer
    ports:
      - 80:80
      - 443:433
    volumes:
      - ./nginx-master-conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nginx-1
      - nginx-2
      - nginx-3 
    restart: always
    networks:
      - internal

  nginx-1:
    image: nginx:latest
    container_name: nginx-1
    volumes:
      - ./nginx-1:/usr/share/nginx/html
    restart: always
    networks:
      - internal

  nginx-2:
    image: nginx:latest
    container_name: nginx-2
    volumes:
      - ./nginx-2:/usr/share/nginx/html
    restart: always
    networks:
      - internal

  nginx-3:
    image: nginx:latest
    container_name: nginx-3
    volumes:
      - ./nginx-3:/usr/share/nginx/html
    restart: always
    networks:
      - internal

networks:
  internal:
    driver: bridge
